image:
  file: .gitpod.Dockerfile

tasks:
  - name: python
    command: |
      gp sync-await awscreds
      bash ./poetry-install.sh
      poetry run start
  - name: awscreds
    openMode: split-right
    command: |
      echo How to start working:
      echo '1) Grab AWS creds from https://dev-portal.internal.equipmentshare.com and paste in this terminal'
      echo '2) gp sync-done awscreds'

ports:
  - port: 5000
    onOpen: open-browser

vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance
    - redhat.vscode-yaml
    - yzhang.markdown-all-in-one
    - bungcip.better-toml

jetbrains:
  pycharm:
    vmoptions: "-Xmx4g"
